include: package:flutter_lints/flutter.yaml

linter:
  rules:
    control_flow_in_finally: true
    avoid_print: true
    unnecessary_this: true
    prefer_final_locals: true
    prefer_const_constructors: true
    unnecessary_null_checks: true
    prefer_is_not_empty: true
analyzer:
  exclude:
    - '*/.g.dart'
    - '*/.freezed.dart'
